name: 'AnnexTube GitHub Pages Deploy'
description: 'Automatically deploy annextube archives to GitHub Pages'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  repo-path:
    description: 'Path to the annextube repository (default: .)'
    required: false
    default: '.'

  github-token:
    description: 'GitHub token for pushing to gh-pages branch (default: GITHUB_TOKEN)'
    required: false

  gh-pages-branch:
    description: 'Target branch name for GitHub Pages (default: gh-pages)'
    required: false
    default: 'gh-pages'

  build-frontend:
    description: 'Build frontend before deployment (default: true)'
    required: false
    default: 'true'

  copy-data:
    description: 'Copy data files (videos/, playlists/) to gh-pages branch (default: true)'
    required: false
    default: 'true'

  annextube-version:
    description: 'Version of annextube to install (default: pinned version, use "latest" for auto-upgrade)'
    required: false
    default: 'git+https://github.com/con/annextube.git@enh-gh_pages#egg=annextube'

  auto-upgrade-frontend:
    description: 'Automatically upgrade to latest annextube frontend (default: false, requires annextube-version="latest")'
    required: false
    default: 'false'

outputs:
  deployment-url:
    description: 'The URL where the site will be deployed'
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: 'composite'
  steps:
    # Install Python and dependencies
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install annextube
      shell: bash
      run: |
        uv pip install --system "${{ inputs.annextube-version }}"

    # Setup Node.js for frontend building
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install git-annex (required for annexed repositories)
    - name: Install git-annex
      shell: bash
      run: |
        # Use neurodebian for latest git-annex
        sudo apt-get update
        sudo apt-get install -y git-annex
        git annex version

    # Configure git
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Run deployment
    - name: Deploy to GitHub Pages
      id: deploy
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO_PATH: ${{ inputs.repo-path }}
        GH_BRANCH: ${{ inputs.gh-pages-branch }}
        BUILD_FRONTEND: ${{ inputs.build-frontend }}
        COPY_DATA: ${{ inputs.copy-data }}
      run: |
        # Use provided token or fall back to automatic GITHUB_TOKEN
        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          GITHUB_TOKEN="$INPUT_GITHUB_TOKEN"
        fi
        export GITHUB_TOKEN

        cd "$REPO_PATH"

        # Configure git to use GITHUB_TOKEN for push
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

        # Detect repository name from GITHUB_REPOSITORY or git remote
        if [ -n "$GITHUB_REPOSITORY" ]; then
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
        else
          REMOTE_URL=$(git remote get-url origin)
          REPO_NAME=$(echo "$REMOTE_URL" | sed -n 's#.*/\([^/]*\)\.git#\1#p' | head -1)
          if [ -z "$REPO_NAME" ]; then
            REPO_NAME=$(echo "$REMOTE_URL" | sed -n 's#.*/\([^/]*\)$#\1#p' | head -1)
          fi
        fi

        echo "Repository name: $REPO_NAME"
        echo "url=https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}/" >> $GITHUB_OUTPUT

        # Build command
        CMD="annextube prepare-ghpages --output-dir . --repo-name $REPO_NAME --gh-branch $GH_BRANCH"

        if [ "$BUILD_FRONTEND" != "true" ]; then
          CMD="$CMD --no-build-frontend"
        fi

        if [ "$COPY_DATA" != "true" ]; then
          CMD="$CMD --no-copy-data"
        fi

        echo "Running: $CMD"
        $CMD

        # Push to gh-pages using GITHUB_TOKEN
        echo "Pushing to $GH_BRANCH branch..."
        git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$GH_BRANCH" --force

        echo "✓ Deployed successfully!"
        echo "Site will be available at: https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}/"
