name: 'AnnexTube GitHub Pages Deploy'
description: 'Automatically deploy annextube archives to GitHub Pages'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  repo-path:
    description: 'Path to the annextube repository (default: .)'
    required: false
    default: '.'

  github-token:
    description: 'GitHub token for pushing to gh-pages branch (default: GITHUB_TOKEN)'
    required: false

  gh-pages-branch:
    description: 'Target branch name for GitHub Pages (default: gh-pages)'
    required: false
    default: 'gh-pages'

  build-frontend:
    description: 'Build frontend before deployment (default: true)'
    required: false
    default: 'true'

  copy-data:
    description: 'Copy data files (videos/, playlists/) to gh-pages branch (default: true)'
    required: false
    default: 'true'

  annextube-version:
    description: 'Version of annextube to install (default: pinned version, use "latest" for auto-upgrade)'
    required: false
    default: 'git+https://github.com/con/annextube.git@enh-gh_pages#egg=annextube'

  auto-upgrade-frontend:
    description: 'Automatically upgrade to latest annextube frontend (default: false, requires annextube-version="latest")'
    required: false
    default: 'false'

  get-annex:
    description: 'Strategy for fetching annexed files: "get" (mandatory, fail if unavailable), "try-get" (optional, keep symlinks if unavailable), "remove-absent" (remove unfetchable symlinks)'
    required: false
    default: 'try-get'

  install-yt-dlp:
    description: 'Install yt-dlp for fetching videos from YouTube URL remotes'
    required: false
    default: 'true'

  annex-remote:
    description: 'Specific git-annex remote to use for fetching content (e.g., "github-lfs"). If not specified, tries all available remotes.'
    required: false
    default: ''

outputs:
  deployment-url:
    description: 'The URL where the site will be deployed'
    value: ${{ steps.deploy.outputs.url }}

runs:
  using: 'composite'
  steps:
    # Install Python and dependencies
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install annextube
      shell: bash
      run: |
        uv pip install --system "${{ inputs.annextube-version }}"

    # Checkout annextube repository to get frontend source
    - name: Checkout annextube for frontend
      uses: actions/checkout@v4
      with:
        repository: 'con/annextube'
        ref: 'enh-gh_pages'
        path: '_annextube_source'

    # Setup Node.js for frontend building
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Install git-annex (required for annexed repositories)
    - name: Install git-annex
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y git-annex git-lfs
        git annex version
        git lfs version

    # Install yt-dlp (for fetching from YouTube URL remotes)
    - name: Install yt-dlp
      if: ${{ inputs.install-yt-dlp == 'true' }}
      shell: bash
      run: |
        pip install yt-dlp
        yt-dlp --version

    # Configure git
    - name: Configure git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Configure git-lfs authentication for fetching from github-lfs remote
    - name: Configure git-lfs authentication
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Use provided token or fall back to automatic GITHUB_TOKEN
        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          TOKEN="$INPUT_GITHUB_TOKEN"
        else
          TOKEN="${GITHUB_TOKEN}"
        fi
        # Configure git credential helper for LFS
        echo "https://x-access-token:${TOKEN}@github.com" > ~/.git-credentials
        git config --global credential.helper store

    # Run deployment
    - name: Deploy to GitHub Pages
      id: deploy
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO_PATH: ${{ inputs.repo-path }}
        GH_BRANCH: ${{ inputs.gh-pages-branch }}
        BUILD_FRONTEND: ${{ inputs.build-frontend }}
        COPY_DATA: ${{ inputs.copy-data }}
        GET_ANNEX: ${{ inputs.get-annex }}
        ANNEX_REMOTE: ${{ inputs.annex-remote }}
        ANNEXTUBE_FRONTEND_DIR: ${{ github.workspace }}/_annextube_source/frontend
      run: |
        # Use provided token or fall back to automatic GITHUB_TOKEN
        if [ -n "$INPUT_GITHUB_TOKEN" ]; then
          GITHUB_TOKEN="$INPUT_GITHUB_TOKEN"
        fi
        export GITHUB_TOKEN

        cd "$REPO_PATH"

        # Configure git to use GITHUB_TOKEN for push
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"

        # Detect repository name from GITHUB_REPOSITORY or git remote
        if [ -n "$GITHUB_REPOSITORY" ]; then
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
        else
          REMOTE_URL=$(git remote get-url origin)
          REPO_NAME=$(echo "$REMOTE_URL" | sed -n 's#.*/\([^/]*\)\.git#\1#p' | head -1)
          if [ -z "$REPO_NAME" ]; then
            REPO_NAME=$(echo "$REMOTE_URL" | sed -n 's#.*/\([^/]*\)$#\1#p' | head -1)
          fi
        fi

        echo "Repository name: $REPO_NAME"
        echo "url=https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}/" >> $GITHUB_OUTPUT

        # Build command
        CMD="annextube prepare-ghpages --output-dir . --repo-name $REPO_NAME --gh-branch $GH_BRANCH"

        if [ "$BUILD_FRONTEND" != "true" ]; then
          CMD="$CMD --no-build-frontend"
        fi

        if [ "$COPY_DATA" != "true" ]; then
          CMD="$CMD --no-copy-data"
        fi

        echo "Running: $CMD"
        $CMD

        # Fetch annexed content if requested
        if [ "$COPY_DATA" = "true" ] && [ "$GET_ANNEX" != "none" ]; then
          echo "Fetching annexed content..."
          git checkout "$GH_BRANCH"

          # Enable specified remote if needed
          if [ -n "$ANNEX_REMOTE" ]; then
            git annex enableremote "$ANNEX_REMOTE" 2>&1 || echo "Remote already enabled or doesn't exist"
            # Reconfigure git-lfs remote to use HTTPS (SSH not available in Actions)
            LFS_URL=$(git config --get "remote.${ANNEX_REMOTE}.url" 2>/dev/null || true)
            if echo "$LFS_URL" | grep -q "git@github.com:"; then
              HTTPS_URL=$(echo "$LFS_URL" | sed 's|git@github.com:|https://github.com/|')
              echo "Reconfiguring $ANNEX_REMOTE URL from SSH to HTTPS: $HTTPS_URL"
              git config "remote.${ANNEX_REMOTE}.url" "$HTTPS_URL"
            fi
          fi

          # Build git annex get command
          ANNEX_CMD="git annex get"
          if [ -n "$ANNEX_REMOTE" ]; then
            ANNEX_CMD="$ANNEX_CMD --from=$ANNEX_REMOTE"
          fi

          case "$GET_ANNEX" in
            get)
              echo "Strategy: mandatory fetch"
              $ANNEX_CMD videos/ playlists/ || {
                echo "ERROR: Failed to fetch all annexed content"
                exit 1
              }
              ;;
            try-get)
              echo "Strategy: optional fetch"
              $ANNEX_CMD videos/ playlists/ || echo "Warning: Some annexed content unavailable"
              ;;
            remove-absent)
              echo "Strategy: remove unfetchable"
              $ANNEX_CMD videos/ playlists/ || true
              ;;
            *)
              echo "Unknown get-annex strategy: $GET_ANNEX"
              exit 1
              ;;
          esac

          # Disable annex filters BEFORE unlock so git doesn't re-pointer files.
          # git-annex v10+ uses filter.annex.process (long-running protocol)
          # which overrides clean/smudge, so we must disable all three.
          # Also strip filter=annex from .gitattributes as belt-and-suspenders.
          if [ -f .gitattributes ]; then
            sed -i '/filter=annex/d' .gitattributes
          fi
          git config --local filter.annex.process ""
          git config --local filter.annex.clean cat
          git config --local filter.annex.smudge cat

          # Unlock ALL annexed files (replaces symlinks with real content)
          git annex unlock . 2>/dev/null || true

          # Resolve non-annex symlinks (e.g. playlist entries -> video dirs)
          # and remove any remaining broken symlinks
          find . -type l 2>/dev/null | while IFS= read -r link; do
            dir=$(dirname "$link")
            target="$dir/$(readlink "$link")"
            if [ -e "$target" ]; then
              # Replace symlink with copy of target
              rm "$link"
              cp -a "$target" "$link"
            elif [ "$GET_ANNEX" = "remove-absent" ]; then
              rm "$link"
            fi
          done

          if ! git diff --quiet || ! git diff --cached --quiet; then
            git add -A
            git commit -m "Update annexed content for GitHub Pages" || true
          fi

          echo "✓ Annexed content processed"
        fi

        # Push gh-pages branch
        echo "Pushing to $GH_BRANCH branch..."

        # Push to gh-pages using GITHUB_TOKEN
        if git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" "$GH_BRANCH" --force; then
          echo "✓ Push successful!"
        else
          echo "ERROR: Push failed with exit code $?"
          exit 1
        fi

        echo "✓ Deployed successfully!"
        echo "Site will be available at: https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}/"
